### ISSUE TITLE
frontend启动报错

### ISSUE THREAD

**Issue by Reiice** [mao888/bluebell#26]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/free-min/-/free-min-2.1.2.tgz - Not found
npm ERR! 404
npm ERR! 404  'free-min@https://registry.npmjs.org/free-min/-/free-min-2.1.2.tgz' is not in this registry.

[2023-07-08T05_04_27_254Z-debug-0.log](https://github.com/mao888/bluebell/files/11988616/2023-07-08T05_04_27_254Z-debug-0.log)

**Comment by mao888** [comment]
free-min@2.1.2，这个包被删除了，现已修复

**Comment by mao888** [comment]
最新版本：https://github.com/mao888/bluebell/releases/tag/v2.2.0

**Comment by Reiice** [comment]
thx
